[net]
git-fetch-with-cli = true
retry = 10

[http]
timeout = 10
check-revoke = false
multiplexing = true

#[build]
#rustflags = ["-C", "target-cpu=native"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+avx2,+aes,+fma"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+avx2,+aes,+fma"]
